# Generated by Django 4.2.23 on 2025-06-22 05:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applied_users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('education', models.CharField(max_length=30)),
                ('program_experience', models.CharField(max_length=20)),
                ('need_to_join', models.TextField()),
                ('carrier_goals', models.TextField()),
                ('referral_code', models.CharField(max_length=15)),
                ('payment_screenshot', models.TextField()),
                ('create_refer', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
